### ISSUE TITLE
GDPR acceptance required (if running in Europe?) else speedtest fails to run...

### ISSUE THREAD

**Issue by n1nj4888** [loganmarchione/docker-speedtest-influxdbv2#1]
Hi, Thanks for this speedtest container!

I noticed the container seems to fail (I think only if in Europe?) with the following error indicating that GDPR acceptance of the speedtest client is required. I've tested the fix which seems to be the following and this then works:

```
# Run Speedtest
print("STATE: Speedtest running")
#my_speed = subprocess.run(['/usr/bin/speedtest', '--accept-license', '--format=json'], stdout=subprocess.PIPE, text=True, check=True)
# Comment out above line and instead add "Accept GDPR flag to the speedtest client"
my_speed = subprocess.run(['/usr/bin/speedtest', '--accept-license', '--accept-gdpr', '--format=json'], stdout=subprocess.PIPE, text=True, check=True)

```

Docker logs error below (before the above fix)...
```
#####
Script starting!
#####
STATE: Starting at 2020-12-27T08:22:45.499357
STATE: Sleep time between runs set to 600 seconds
STATE: Checking environment variables...
STATE: Connecting to InfluxDB...
STATE: Running database check
STATE: Connection pass
STATE: Loop running at 2020-12-27T08:22:45.508155
STATE: Speedtest running
==============================================================================

You may only use this Speedtest software and information generated
from it for personal, non-commercial use, through a command line
interface on a personal computer. Your use of this software is subject
to the End User License Agreement, Terms of Use and Privacy Policy at
these URLs:

     https://www.speedtest.net/about/eula
     https://www.speedtest.net/about/terms
     https://www.speedtest.net/about/privacy

==============================================================================

License acceptance recorded. Continuing.

==============================================================================

Ookla collects certain data through Speedtest that may be considered
personally identifiable, such as your IP address, unique device
identifiers or location. Ookla believes it has a legitimate interest
to share this data with internet providers, hardware manufacturers and
industry regulators to help them understand and create a better and
faster internet. For further information including how the data may be
shared, where the data may be transferred and Ookla's contact details,
please see our Privacy Policy at:

       http://www.speedtest.net/privacy

==============================================================================

To accept the message please run speedtest interactively or use the following:

    speedtest --accept-gdpr
Traceback (most recent call last):
  File "./speedtest.py", line 128, in <module>
    speedtest()
  File "./speedtest.py", line 46, in speedtest
    my_speed = subprocess.run(['/usr/bin/speedtest', '--accept-license', '--format=json'], stdout=subprocess.PIPE, text=True, check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/speedtest', '--accept-license', '--format=json']' returned non-zero exit status 1.


```

**Comment by loganmarchione** [comment]
I can fix this later tonight. The docs for this app are not good and there are no devs to ask.

**Comment by loganmarchione** [comment]
I just added `--accept-gdpr` and pushed 0.0.11 to DockerHub. Test it and let me know here.

**Comment by n1nj4888** [comment]
Thanks @loganmarchione - Tested and now works!
